### ISSUE TITLE
Error Stacktrace HCFoodBaby_2_LocationDistribution

### ISSUE THREAD

**Issue by axi92** [robotex140/Hydrocraft#56]
**Describe the bug**
Every time I join my server I get this error.

**To Reproduce**
Debug mode enabled

**Expected behavior**
No errors

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1394837/166103700-4af2d730-c77e-4e6c-9db7-516782f20136.png)
When I hit F11 the next break happens:
![grafik](https://user-images.githubusercontent.com/1394837/166103737-d3084896-c216-43c3-a484-41a2a59245cc.png)

**Additional context**

**Comment by HugoQwerty** [comment]
I've seen this reported a few times, but never found the cause.  I suspect another mod is causing it.

Can you provide a list of all the mods you have installed?

**Comment by axi92** [comment]
Sure:

```
      MOD_NAMES: "PZRespawnRedux;BetterSortCC;manageContainers;ObviousRecipeChippedStone;ForagingBuff01;ATA_Bus;TMC_Trolley;VehiclePartsRepair;modoptions;TheStar;VehicleRecycling;DisableCarWear;82oshkoshM911;Respawn;ExpImp;Hydrocraft;Skateboard;OutTheWindow;TrueActionsDancing;RV5Vegetabletoseeds;cropsNeverRot;VPR_RecyclingCenter;VehicleRepairOverhaul;POETConstructionBuff;POETExtremeBarricades;POETIgnoredLogWalls;amclub;ChangeSandBox;BSHydrocraft;isoContainers;waterPipes;CraftHelper41;EasyPacking;EasyPackingHC;fhqExpVehSpawn;MoreCLR_desc4mood;NamedSkillVHSTapes;MinimalDisplayBars"
      MOD_WORKSHOP_IDS: "2685600088;2313387159;2650547917;2704468416;2700569885;2592358528;2478768005;1558779191;2169435993;2619072426;2289429759;2444374984;2618213077;2687842971;2655563133;2778991696;2728300240;2659216714;2648779556;2774670617;2728416041;2713055926;2757712197;2508717129;2778576730;2670674997;2735651677;2625625421;2464581798;2186592938;2438225189;2793164190;2763647806;2732294885;2004998206"
```

**Comment by axi92** [comment]
Maybe its the mod EasyPacking?


```
LOG  : Lua         , 1651524797167> 15,864,705,795> Loading: steamapps/workshop/content/108600/2438225189/mods/EasyPackingHC/media/lua/server/items/GidOrganizedStorage_ProceduralDistribution.lua
LOG  : General     , 1651524797170> 15,864,705,812> -------------------------------------------------------------
attempted index: items of non-table: null

LOG  : General     , 1651524797204> 15,864,705,833> -----------------------------------------
STACK TRACE
-----------------------------------------
function: GidOrganizedStorage_ProceduralDistribution.lua -- file: GidOrganizedStorage_ProceduralDistribution.lua line # 51

ERROR: General     , 1651524797207> 15,864,705,835> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: items of non-table: null at KahluaThread.tableget line:1689.
LOG  : General     , 1651524797238> 15,864,705,867> -----------------------------------------
STACK TRACE
-----------------------------------------
function: GidOrganizedStorage_ProceduralDistribution.lua -- file: GidOrganizedStorage_ProceduralDistribution.lua line # 51

ERROR: General     , 1651524797207> 15,864,705,836> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: items of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
        at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
        at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
        at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:554)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:500)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:486)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:333)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:260)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1417)
        at zombie.network.GameServer.main(GameServer.java:705)
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE:  java.lang.RuntimeException
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: java.lang.RuntimeException:
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: at GidOrganizedStorage_ProceduralDistribution.lua:51
```

**Comment by axi92** [comment]
Here is the full server log with the stacktraces:

```
LOG  : Lua         , 1651524797105> 15,864,705,734> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/HCLoot.lua
LOG  : Lua         , 1651524797110> 15,864,705,738> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/HCMRE.lua
LOG  : Lua         , 1651524797113> 15,864,705,741> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/HuntingHCExtra.lua
LOG  : Lua         , 1651524797142> 15,864,705,770> Loading: steamapps/workshop/content/108600/2618213077/mods/82oshkoshM911/media/lua/server/Items/82oshkoshitemDistro.lua
LOG  : Lua         , 1651524797145> 15,864,705,774> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/Distributions_HC.lua
LOG  : Lua         , 1651524797161> 15,864,705,790> Loading: steamapps/workshop/content/108600/2757712197/mods/Vehicle Repair Overhaul/media/lua/server/Items/FixAFlat_ProceduralDistributions.lua
LOG  : Lua         , 1651524797164> 15,864,705,792> Loading: steamapps/workshop/content/108600/2438225189/mods/EasyPackingHC/media/lua/server/items/GidOrganizedStorage_Distribution.lua
LOG  : Lua         , 1651524797167> 15,864,705,795> Loading: steamapps/workshop/content/108600/2438225189/mods/EasyPackingHC/media/lua/server/items/GidOrganizedStorage_ProceduralDistribution.lua
LOG  : General     , 1651524797170> 15,864,705,812> -------------------------------------------------------------
attempted index: items of non-table: null

LOG  : General     , 1651524797204> 15,864,705,833> -----------------------------------------
STACK TRACE
-----------------------------------------
function: GidOrganizedStorage_ProceduralDistribution.lua -- file: GidOrganizedStorage_ProceduralDistribution.lua line # 51

ERROR: General     , 1651524797207> 15,864,705,835> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: items of non-table: null at KahluaThread.tableget line:1689.
LOG  : General     , 1651524797238> 15,864,705,867> -----------------------------------------
STACK TRACE
-----------------------------------------
function: GidOrganizedStorage_ProceduralDistribution.lua -- file: GidOrganizedStorage_ProceduralDistribution.lua line # 51

ERROR: General     , 1651524797207> 15,864,705,836> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: items of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
        at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
        at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
        at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:554)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:500)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:486)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:333)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:260)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1417)
        at zombie.network.GameServer.main(GameServer.java:705)
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE:  java.lang.RuntimeException
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: java.lang.RuntimeException:
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: at GidOrganizedStorage_ProceduralDistribution.lua:51

LOG  : Lua         , 1651524797280> 15,864,705,909> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCAnimals_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797283> 15,864,705,911> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCAnimals_2_LocationDistributions.lua
LOG  : Lua         , 1651524797289> 15,864,705,918> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCAstronomy_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797290> 15,864,705,919> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCAstronomy_2_LocationDistributions.lua
LOG  : Lua         , 1651524797292> 15,864,705,921> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCAuto_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797293> 15,864,705,922> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCAuto_2_LocationDistributions.lua
LOG  : Lua         , 1651524797296> 15,864,705,925> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBarrel_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797298> 15,864,705,927> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBarrel_2_LocationDistributions.lua
LOG  : Lua         , 1651524797302> 15,864,705,930> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBathroom_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797304> 15,864,705,963> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBathroom_2_LocationDistributions.lua
LOG  : Lua         , 1651524797342> 15,864,705,970> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBattery_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797344> 15,864,705,973> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBattery_2_LocationDistributions.lua
LOG  : Lua         , 1651524797370> 15,864,705,999> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBottle_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797376> 15,864,706,005> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBottle_2_LocationDistributions.lua
LOG  : Lua         , 1651524797379> 15,864,706,007> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBugs_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797380> 15,864,706,009> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCBugs_2_LocationDistributions.lua
LOG  : Lua         , 1651524797383> 15,864,706,011> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCamping_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797384> 15,864,706,013> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCamping_2_LocationDistributions.lua
LOG  : Lua         , 1651524797386> 15,864,706,015> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCarpentry_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797388> 15,864,706,016> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCarpentry_2_LocationDistributions.lua
LOG  : Lua         , 1651524797389> 15,864,706,018> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCats_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797390> 15,864,706,019> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCats_2_LocationDistributions.lua
LOG  : Lua         , 1651524797391> 15,864,706,020> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCentrifuge_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797397> 15,864,706,026> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCentrifuge_2_LocationDistributions.lua
LOG  : Lua         , 1651524797452> 15,864,706,080> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCChemistry_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797465> 15,864,706,094> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCChemistry_2_LocationDistributions.lua
LOG  : Lua         , 1651524797468> 15,864,706,096> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCinema_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797469> 15,864,706,098> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCinema_2_LocationDistributions.lua
LOG  : Lua         , 1651524797472> 15,864,706,100> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCleaning_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797475> 15,864,706,104> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCleaning_2_LocationDistributions.lua
LOG  : Lua         , 1651524797479> 15,864,706,108> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCClothing_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797481> 15,864,706,109> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCClothing_2_LocationDistributions.lua
LOG  : Lua         , 1651524797483> 15,864,706,111> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCookbooks_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797486> 15,864,706,115> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCCookbooks_2_LocationDistributions.lua
LOG  : Lua         , 1651524797490> 15,864,706,119> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCDrug_Tobacco_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797540> 15,864,706,169> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCDrug_Tobacco_2_LocationDistributions.lua
LOG  : Lua         , 1651524797559> 15,864,706,187> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCElectronics_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797566> 15,864,706,197> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCElectronics_2_LocationDistributions.lua
LOG  : Lua         , 1651524797645> 15,864,706,273> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFlags_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797646> 15,864,706,275> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFlags_2_LocationDistributions.lua
LOG  : Lua         , 1651524797650> 15,864,706,279> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodBaby_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797652> 15,864,706,280> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodBaby_2_LocationDistributions.lua
LOG  : General     , 1651524797658> 15,864,706,286> -------------------------------------------------------------
attempted index: bin of non-table: null

LOG  : General     , 1651524797658> 15,864,706,287> -----------------------------------------
STACK TRACE
-----------------------------------------
function: insertItemListsInDistribution -- file: HCDistributionFunctions.lua line # 207
function: HCFoodBaby_2_LocationDistributions.lua -- file: HCFoodBaby_2_LocationDistributions.lua line # 22

LOG  : General     , 1651524797661> 15,864,706,290> -----------------------------------------
STACK TRACE
-----------------------------------------
function: insertItemListsInDistribution -- file: HCDistributionFunctions.lua line # 207
function: HCFoodBaby_2_LocationDistributions.lua -- file: HCFoodBaby_2_LocationDistributions.lua line # 22

ERROR: General     , 1651524797659> 15,864,706,288> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: bin of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1651524797660> 15,864,706,289> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: bin of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
        at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
        at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
        at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:554)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:500)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:486)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:333)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:260)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1417)
        at zombie.network.GameServer.main(GameServer.java:705)
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE:  java.lang.RuntimeException
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: java.lang.RuntimeException:
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: at insertItemListsInDistribution:207
at HCFoodBaby_2_LocationDistributions.lua:22

LOG  : Lua         , 1651524797665> 15,864,706,294> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodBar_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797667> 15,864,706,296> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodBar_2_LocationDistributions.lua
LOG  : Lua         , 1651524797671> 15,864,706,300> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodBreakfast_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797673> 15,864,706,301> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodBreakfast_2_LocationDistributions.lua
LOG  : Lua         , 1651524797678> 15,864,706,306> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodCandy_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797743> 15,864,706,371> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCFoodCandy_2_LocationDistributions.lua
LOG  : Lua         , 1651524797754> 15,864,706,383> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCLeisureBooks_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797756> 15,864,706,385> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCLeisureBooks_2_LocationDistributions.lua
ERROR: General     , 1651524797770> 15,864,706,399> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: crate of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1651524797771> 15,864,706,400> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: crate of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
LOG  : Lua         , 1651524797766> 15,864,706,394> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCLoot_1_RelativeDistributions.lua
LOG  : Lua         , 1651524797767> 15,864,706,396> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/HCLoot_2_LocationDistributions.lua
LOG  : General     , 1651524797769> 15,864,706,398> -------------------------------------------------------------
attempted index: crate of non-table: null

LOG  : General     , 1651524797770> 15,864,706,398> -----------------------------------------
STACK TRACE
-----------------------------------------
function: createProcDistributionContainer -- file: HCDistributionFunctions.lua line # 266
function: HCLoot_2_LocationDistributions.lua -- file: HCLoot_2_LocationDistributions.lua line # 9

        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
        at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
        at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
        at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:554)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:500)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:486)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:333)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:260)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1417)
        at zombie.network.GameServer.main(GameServer.java:705)
LOG  : General     , 1651524797843> 15,864,706,471> -----------------------------------------
STACK TRACE
-----------------------------------------
function: createProcDistributionContainer -- file: HCDistributionFunctions.lua line # 266
function: HCLoot_2_LocationDistributions.lua -- file: HCLoot_2_LocationDistributions.lua line # 9

LOG  : Lua         , 1651524797852> 15,864,706,480> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Items/ProceduralDistributions_HC.lua
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE:  java.lang.RuntimeException
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: java.lang.RuntimeException:
May 02, 2022 8:53:17 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: at createProcDistributionContainer:266
at HCLoot_2_LocationDistributions.lua:9

LOG  : General     , 1651524798045> 15,864,706,673> >>alive
LOG  : Lua         , 1651524798047> 15,864,706,676> Loading: steamapps/workshop/content/108600/2648779556/mods/TrueActionsDancing/media/lua/server/Items/TADItemDistributions.lua
LOG  : General     , 1651524798059> 15,864,706,688> INFO: TRUE ACTIONS DANCING. Magazines WILL spawn
LOG  : Lua         , 1651524798063> 15,864,706,691> Loading: steamapps/workshop/content/108600/2648779556/mods/TrueActionsDancing/media/lua/server/Items/TADKosmoItemDistributions.lua
LOG  : Lua         , 1651524798070> 15,864,706,699> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/JunkyardExtra.lua
LOG  : Lua         , 1651524798079> 15,864,706,708> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Library/HCLibraryZones.lua
LOG  : Lua         , 1651524798084> 15,864,706,713> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/Locks/LockCraftingServer.lua
LOG  : Lua         , 1651524798086> 15,864,706,715> Loading: steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/server/PFG.lua
LOG  : Lua         , 1651524798089> 15,864,706,718> Loading: steamapps/workshop/content/108600/2508717129/mods/Stronger Constructions/media/lua/server/POETDurableConstructs.lua
LOG  : Lua         , 1651524798093> 15,864,706,721> Loading: steamapps/workshop/content/108600/2508717129/mods/Stronger Constructions - Extreme/media/lua/server/POETStrongBarricades.lua
LOG  : General     , 1651524798094> 15,864,706,723> -------------------------------------------------------------
attempted index: perform of non-table: null

LOG  : General     , 1651524798095> 15,864,706,723> -----------------------------------------
STACK TRACE
-----------------------------------------
function: POETStrongBarricades.lua -- file: POETStrongBarricades.lua line # 7

ERROR: General     , 1651524798095> 15,864,706,724> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: perform of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1651524798095> 15,864,706,724> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: perform of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
        at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
        at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
        at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:554)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:500)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:486)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:333)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:260)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1417)
        at zombie.network.GameServer.main(GameServer.java:705)
LOG  : General     , 1651524798097> 15,864,706,725> -----------------------------------------
STACK TRACE
-----------------------------------------
function: POETStrongBarricades.lua -- file: POETStrongBarricades.lua line # 7

May 02, 2022 8:53:18 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE:  java.lang.RuntimeException
May 02, 2022 8:53:18 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: java.lang.RuntimeException:
May 02, 2022 8:53:18 PM zombie.Lua.LuaManager RunLuaInternal
SEVERE: at POETStrongBarricades.lua:7
```

**Comment by robotex140** [comment]
yes it seems like it is caused by easypacking. easy packing already causes errors when you are just using easy packing with vanilla.
